# -*- coding: utf-8 -*-
"""LVADSUSR196_Venkat Vikash V.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YybgmejdsmGqac57-s_o3KTNiQ-uFE83

**Importing the necessary libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**Question 1**

Importing the dataset
"""

ipl = pd.read_csv("/content/Final Dataset - IPL.csv")

ipl.info()

"""**Question 2**

Checking for null values
"""

ipl.isnull().sum()
#There are no null values

ipl.head()

"""

1.   Null values present in venue would be replaced by "Not given", if numerical values like innings score are missing then they would be replaced with the average first and second innings score.
2.   If toss decision and other string values are missing then meaningful string values like "Not given" would be replaced as that particular row could contribute to the overall anaysis of the data.

"""

ipl = ipl.dropna()

"""Removing Duplicates"""

ipl.duplicated().sum() #There are no duplicates present

"""**Question 3**

Descriptive Statistics
"""

ipl[['first_ings_score','first_ings_wkts','second_ings_score','second_ings_wkts','highscore']].describe()

#Finding Variance
var_first = ipl['first_ings_score'].var()
var_second = ipl['second_ings_score'].var()

var_first_wkts = ipl['first_ings_wkts'].var()
var_second_wkts = ipl['second_ings_wkts'].var()

high = ipl['highscore'].var()

print("First and Second innigns variance",var_first,var_second)
print("First and Second innings wickets variance",var_first_wkts,var_second_wkts)
print("Variance of high score",high)

#Finding Variance
mode_first = ipl['first_ings_score'].mode()
mode_second = ipl['second_ings_score'].mode()

mode_first_wkts = ipl['first_ings_wkts'].mode()
mode_second_wkts = ipl['second_ings_wkts'].mode()

high = ipl['highscore'].mode()
print("First and Second innigns Mode",mode_first,mode_second)
print("First and Second innings wickets Mode",mode_first_wkts,mode_second_wkts)
print("Mode of high score",high)

"""From the above statistical measures, we could understand the following:


*   During the matches played, the average first innings
score was found to be 171 and the average second innings score was found to be 158.54. This means that the teams found it diffcult to chase is matches.


*   The maximum first innings score was 222 and the minimum first innings score was 68. The maximum second innigns score was 211 and the minimum second innings score was 72.



*   We could see that the standard deviation of the data is relatively low, signifying that the data does not significantly differ from one another.

**Question 4**

**Data Visualisation**

Pie chart

Distribution of Venue across the matches
"""

venue = ipl['venue'].value_counts()
plt.title("Venues played in Matches")
plt.pie(venue,labels = venue.index)

"""From this graph we could infer that the matches were fairly distrubuted among the stadiums in Mumbai, with stadium in pune coming next, and then the Eden gardens and the Narendra modi stadium

Scatter plot
"""

x = ipl["first_ings_score"]
y = ipl["second_ings_wkts"]
plt.title("First innings Score vs Second innings Wickets")
plt.xlabel("Scores")
plt.ylabel("Wickets")
plt.scatter(x,y)

"""From the above plot we could see that there is a small positive correlation between first innings score and second innings wickets indicating more wickets were fallen in the second innings.

Histogram

Box plot of second innings score
"""

second_ings = ipl["second_ings_score"]
plt.boxplot(second_ings)

"""Box plot helps us in finding outliers, by plotting the second innings scores we could see that there two outliers in the range of 60-80

Bar Graph

Distribution of match winners
"""

win = ipl["match_winner"].value_counts()
x = win.keys()
plt.figure(figsize=(10,10))
plt.title("Teams with number of wins")
plt.xlabel("Teams")
plt.ylabel("Wins")
plt.bar(x,height =win)

"""**Histogram**"""

first_ings_score = ipl['first_ings_score']
plt.title("Histogram First innings score")
plt.xlabel("X-axis")
plt.hist(first_ings_score)

"""**Question 5**

Correlation
"""

count_toss = ipl['toss_winner'].value_counts()
wins_if_toss = ipl[ipl["toss_winner"]==ipl["match_winner"]]
wins = wins_if_toss["match_winner"].value_counts()
corr = np.corrcoef(count_toss,wins)

sns.heatmap(corr,annot=True)

"""we could see that the toss wins and the match wins are highly correlated to one another

Correlation between various factors
"""

cor = ipl[['first_ings_score','first_ings_wkts','second_ings_score','second_ings_wkts','highscore']].corr()
sns.heatmap(cor,annot=True)

"""**Question 6**

Finding out outliers in the dataset using the IQR method
"""

#Inter Quartile Range
Q1 = ipl["first_ings_score"].quantile(0.25)
Q3 = ipl["first_ings_score"].quantile(0.75)

IQR = Q3-Q1

lower_bound = ipl['first_ings_score']-1.5*IQR
upper_bound = ipl['first_ings_score']+1.5*IQR

df_outlier = ipl[(ipl['first_ings_score']>lower_bound) | (ipl['first_ings_score']<upper_bound)]

"""It is important to know that there are outliers in the data, in this particular data set we could assume the teams with a very high score and very low score, i.e way less than the average could be considered as outliers. It is not recommeneded to remove them, as they would affect the overall nature of the data."""

first_ings = ipl["first_ings_score"]
plt.boxplot(first_ings)

"""**Question 7**"""

df = ipl.groupby(['venue','stage'])["match_winner"].value_counts()
df.head()

df = ipl.groupby(['venue','player_of_the_match'])['player_of_the_match'].count().sort_values(ascending=False)

df1 = ipl.groupby(['stage','player_of_the_match'])['player_of_the_match'].count().sort_values(ascending=False)

print("Best player performances across venues",df)

print("Best player performances across stages",df1)

"""**Question 8**"""

player = ipl["player_of_the_match"].value_counts()
player = player.sort_values(ascending=False)
player.head(3)

"""We could see that the top 3 players with the number of man of the mathes are kuldeep, jos buttler and hardik pandya. We could see that the player with the man of the match usually belonged to the winning team.

Players with most best bowling figures
"""

best_bowling = ipl["best_bowling"].value_counts()
best_bowling.head()

"""**Summary**

*   From the above data we could that the data is well cleaned and has no null values or duplicates.

*   We could also infer that the team with the most number of wins is Gujarat and the team with the least number of wins is tied with Chennai and Mumbai with 4.

*   We could see that the teams who won the toss, had a good impact on the result of the game.

*   We could also infer that team which batted second had lost more wickets than the team which batted first(could infer from the scatter plot).
*   Player with the most number of man of the matches is Kuldeep (4).


*   The average first innings score was considerably higher than the average second innings score (by 20 runs).
"""