# -*- coding: utf-8 -*-
"""IA_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Y2FAWf-Og9fTNO1PwG4VpzMDWiz954l

**SECTION 1**

**Question 1**
"""

def area(length,width):
  return length*width

def categorize(area):
  if area<100:
    print("The area of the property is Small")
  elif area>=100 and area<500:
    print("The area of the property is Medium")
  else:
    print("The area of the property is Large")

length = float(input("Enter the length of the plot in meters: "))
width = float(input("Enter the width of the plot in meters : "))

A = area(length,width)
print("Area of the plot is: ",A,"meters")
categorize(A)

"""**Question 2**"""

# Calculate BMI
def BMI(weight,height):
  return weight/(height/100)**2

def health_advice(BMI):
  if BMI<18:
    print("Your BMI suggests that you are underweight, please be on a calorire surplus and workout more")
  if BMI>=18 and BMI<25:
    print("Your BMI suggests that you are in optimal condition do work out a bit more, be on a calorie maintainance")
  if BMI>25:
    print("Your BMI suggests that you are in overweight,workout without, be on a calorie defecit")

weight = float(input("Enter the weight in kg: "))
height = float(input("Enter the height in cm : "))

BMI = BMI(weight,height)
print("Your BMI is :",BMI)

health_advice(BMI)

"""**Question 3**"""

students_dict = {1:{"Maths:A","Science:B","Social:C"},2:{"Maths:C","Science:A","Social:C"},3:{"Maths:A","Science:D","Social:C"},4:{"Maths:A","Science:B","Social:C"}}

def add_student():
  print

"""**SECTION 2**

**QUESTION 4**
"""

def movie_recommender(age,movies):
  if age<13:
    print("Your are below 13 so here are your recommended movies: ")
    for key in movies.keys():
      if movies[key] == "U":
        print(key)

  elif age>=13 and age<18:
      print("Your are below 18 so here are your recommended movies: ")
      for key in movies.keys():
        if movies[key] == "U/A" or movies[key] == "U":
          print(key)

  elif age>=18:
    print("Your are above 18 so here are your recommended movies: ")
    for key in movies.keys():
        print(key)

# Assuming that there are movies with the following content ratings
movies = {"Movie 1":"A","Movie 2":"U","Movie 3":"U/A","Movie 4":"U","Movie 5":"U/A","Movie 6":"A"}

age = int(input("Enter your age: "))

movie_recommender(age,movies)

"""**Question 5**"""

#Specific list of even numbered email ids
emp_ids = []
for i in range(100,200):
  if i%2 == 0:
    emp_ids.append(i)

print("The list of subscriber ids are: ",emp_ids)

"""**Question 6**"""

def password_checker():
  p = "mypassword"
  while True:
    ps = input("Enter the password")
    if p == ps:
      print("Sucessful you have access to the database")
      break
    else:
      print("Incorrect password try again")

password_checker()

"""**Question 7**"""

import statistics as st

customer_scores = [10,23,342,55,67,89,55]

def average(score):
  return sum(customer_scores)/len(customer_scores)

print(average(customer_scores))

"""**Question 8**"""

# Counting vowels

def vowel_count(text):
  count = 0
  text.lower()
  for i in range(len(text)):
    if text[i] == 'a' or text[i] == 'e' or text[i] == 'i' or text[i] == 'o' or text[i] == 'u':
      count+=1
  return count

text = input("Enter any text")
count_of_vowels = vowel_count(text)
print("The number of vowels in this text is: ",count_of_vowels)

"""**Question 9**"""



"""**Question 10**"""

def savings(acc,username,amount):
  for key in acc.keys():
    if key == username:
      acc[key]+=amount
      print("The savings interest is 5%",acc[key])

def repayment(acc,username,amount):
    for key in acc.keys():
      if key == username:
        print("The repayment is",amount)

acc = {"username1":1000,"username2":3000,"username3":5000}
while True:
  choice = 0
  print("Enter 1 for savings, Enter 2 for repayment: ")
  try:
    if choice ==1:
      name = input("Enter your username")
      amt  = int(input("Enter amount"))
      savings(acc,name,amt)

    elif choice ==2:
      name = input("Enter your username")
      amt  = int(input("Enter amount to be repayed"))
      savings(acc,name,amt)

"""**Question 11**"""

name = input("Enter the name: ")
if type(name)!= "str":
  raise NameError

"""**Question 12**"""

def add(num1,num2):
  return num1+num2

def sub(num1,num2):
  return num1-num2

def mul(num1,num2):
  return num1*num2

def div(num1,num2):
  return num1/num2

num1 = int(input("Enter 1st number"))
num2 = int(input("Enter 2nd number"))
choice = int(input("1 for add 2 for sub 3 for mul4 for div 5 for exit"))

if choice == 1:
  print(add(num1,num2))

elif choice == 2:
  print(sub(num1,num2))

elif choice == 3:
  print(mul(num1,num2))

elif choice == 4:
  if num2 == 0:
    print("Division cannot be performed with denominator as 0")
  else:
    print(div(num1,num2))

elif choice == 5:
  print("Exiting")

else:
  print("Invalid choice")

"""**Question 13**"""

import datetime
def log_time():
  with open("logtime.txt",'w') as file:
    file.write(str(datetime.datetime.now()))

  print("Data logged in successfully")

log_time()

"""**Question 14**"""

def read_log(filename):
    with open(filename, 'r') as file:
        return file.read()

read_log("logtime.txt")

"""**Question 15**"""

def read_write(filename):
      with open(filename, 'w') as file:
        return file.write("This is the new stock update")


read_write("logtime.txt")