# -*- coding: utf-8 -*-
"""LVADSUSR196_Venkat_Vikash_V_final_Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VqL9N9EoIqe0ppAznEDHTv52iHsJEsXw
"""

#IMPORTS FOR EVERYTHING
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import seaborn as sns

df = pd.read_csv("/content/penguins_classification.csv")

df.head()

"""**HANDLING NULL VALUES AND OUTLIERS**"""

df.isnull().sum()

#Treating null value
median = df['bill_depth_mm'].median()
df['bill_depth_mm'] = df['bill_depth_mm'].fillna(median)

df.duplicated().sum()

"""**CHECKING FOR OUTLIERS**"""

sns.boxplot(df)
#There are minimum number of outliers

"""**EDA**"""

sns.pairplot(df)

"""**CORRELATION**"""

corr = df.corr(numeric_only = True)
sns.heatmap(corr,annot=True)

"""**ONE HOT ENCODING**"""

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])
df['island'] = le.fit_transform(df['island'])

#Using bill length and depth and body mass
X = df[['bill_length_mm','bill_depth_mm','body_mass_g']]
y = df['species']

"""**SCALING**"""

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

"""**RANDOM FOREST CLASSIFIER**"""

#Train test split and model
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
model = RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

#CONFUSION MATRIX AND CLASSIFCATION REPORT
#WITHOUT TRANSFORMING TARGET VARIABLE
conf_matrix = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(conf_matrix)

print("Classification Report:")
print(classification_report(y_test, y_pred))